default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: elephant
  host: localhost

development:
  <<: *default
  database: own_database

test:
  <<: *default
  database: own_database

production:
  <<: *default
  database: own_database
  username: own_database_123
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
